// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opbtbgtzinpysokwfaqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wYnRiZ3R6aW5weXNva3dmYXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjEyODQsImV4cCI6MjA2OTM5NzI4NH0.CvSW-d0IXWAJ1cpPGK5-gz0jVT3ltFDZsz1x1qTzQv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});